### ISSUE TITLE
Implement mlib example ranking_metrics_example.py

### ISSUE THREAD

**Issue by Brian-P-Burns** [EclairJS/eclairjs-nashorn#100]

**Comment by Brian-P-Burns** [comment]
Merged branch into master.  This introduced a number of changes including changing the serialization to and from java to javascript into nashorn.  This should have been broken up into several issues.

**Comment by doronrosenberg** [comment]
I get this every so often running it:

```
Dorons-MacBook-Pro-2:eclairjs-nashorn doronrosenberg$ bin/eclairjs.sh examples/mllib/ranking_metrics_example.js
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
16/03/03 09:03:47 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/03/03 09:03:48 INFO Remoting: Starting remoting
16/03/03 09:03:48 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriverActorSystem@192.168.1.124:50205]
16/03/03 09:03:51 WARN BLAS: Failed to load implementation from: com.github.fommil.netlib.NativeSystemBLAS
16/03/03 09:03:51 WARN BLAS: Failed to load implementation from: com.github.fommil.netlib.NativeRefBLAS
16/03/03 09:03:51 WARN LAPACK: Failed to load implementation from: com.github.fommil.netlib.NativeSystemLAPACK
16/03/03 09:03:51 WARN LAPACK: Failed to load implementation from: com.github.fommil.netlib.NativeRefLAPACK
Precision at 1 = 0.3
NDCG at 1 = 0.3
Precision at 3 = 0.36666666666666664
NDCG at 3 = 0.35307212739772437
Precision at 5 = 0.4
16/03/03 09:03:53 ERROR Executor: Exception in task 1.0 in stage 419.0 (TID 349)
java.lang.ArrayIndexOutOfBoundsException: 4
    at scala.runtime.ScalaRunTime$.array_apply(ScalaRunTime.scala:71)
    at org.apache.spark.mllib.evaluation.RankingMetrics$$anonfun$ndcgAt$2.apply(RankingMetrics.scala:143)
    at org.apache.spark.mllib.evaluation.RankingMetrics$$anonfun$ndcgAt$2.apply(RankingMetrics.scala:132)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at org.apache.spark.util.StatCounter.merge(StatCounter.scala:53)
    at org.apache.spark.util.StatCounter.<init>(StatCounter.scala:35)
    at org.apache.spark.util.StatCounter$.apply(StatCounter.scala:144)
    at org.apache.spark.rdd.DoubleRDDFunctions$$anonfun$stats$1$$anonfun$apply$1.apply(DoubleRDDFunctions.scala:42)
    at org.apache.spark.rdd.DoubleRDDFunctions$$anonfun$stats$1$$anonfun$apply$1.apply(DoubleRDDFunctions.scala:42)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
    at org.apache.spark.scheduler.Task.run(Task.scala:89)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
16/03/03 09:03:53 ERROR Executor: Exception in task 0.0 in stage 419.0 (TID 348)
java.lang.ArrayIndexOutOfBoundsException: 4
    at scala.runtime.ScalaRunTime$.array_apply(ScalaRunTime.scala:71)
    at org.apache.spark.mllib.evaluation.RankingMetrics$$anonfun$ndcgAt$2.apply(RankingMetrics.scala:143)
    at org.apache.spark.mllib.evaluation.RankingMetrics$$anonfun$ndcgAt$2.apply(RankingMetrics.scala:132)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at org.apache.spark.util.StatCounter.merge(StatCounter.scala:53)
    at org.apache.spark.util.StatCounter.<init>(StatCounter.scala:35)
    at org.apache.spark.util.StatCounter$.apply(StatCounter.scala:144)
    at org.apache.spark.rdd.DoubleRDDFunctions$$anonfun$stats$1$$anonfun$apply$1.apply(DoubleRDDFunctions.scala:42)
    at org.apache.spark.rdd.DoubleRDDFunctions$$anonfun$stats$1$$anonfun$apply$1.apply(DoubleRDDFunctions.scala:42)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
    at org.apache.spark.scheduler.Task.run(Task.scala:89)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
16/03/03 09:03:53 WARN TaskSetManager: Lost task 1.0 in stage 419.0 (TID 349, localhost): java.lang.ArrayIndexOutOfBoundsException: 4
    at scala.runtime.ScalaRunTime$.array_apply(ScalaRunTime.scala:71)
    at org.apache.spark.mllib.evaluation.RankingMetrics$$anonfun$ndcgAt$2.apply(RankingMetrics.scala:143)
    at org.apache.spark.mllib.evaluation.RankingMetrics$$anonfun$ndcgAt$2.apply(RankingMetrics.scala:132)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at org.apache.spark.util.StatCounter.merge(StatCounter.scala:53)
    at org.apache.spark.util.StatCounter.<init>(StatCounter.scala:35)
    at org.apache.spark.util.StatCounter$.apply(StatCounter.scala:144)
    at org.apache.spark.rdd.DoubleRDDFunctions$$anonfun$stats$1$$anonfun$apply$1.apply(DoubleRDDFunctions.scala:42)
    at org.apache.spark.rdd.DoubleRDDFunctions$$anonfun$stats$1$$anonfun$apply$1.apply(DoubleRDDFunctions.scala:42)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
    at org.apache.spark.scheduler.Task.run(Task.scala:89)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

16/03/03 09:03:53 ERROR TaskSetManager: Task 1 in stage 419.0 failed 1 times; aborting job
Exception in thread "main" java.lang.RuntimeException: org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 419.0 failed 1 times, most recent failure: Lost task 1.0 in stage 419.0 (TID 349, localhost): java.lang.ArrayIndexOutOfBoundsException: 4
    at scala.runtime.ScalaRunTime$.array_apply(ScalaRunTime.scala:71)
    at org.apache.spark.mllib.evaluation.RankingMetrics$$anonfun$ndcgAt$2.apply(RankingMetrics.scala:143)
    at org.apache.spark.mllib.evaluation.RankingMetrics$$anonfun$ndcgAt$2.apply(RankingMetrics.scala:132)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at org.apache.spark.util.StatCounter.merge(StatCounter.scala:53)
    at org.apache.spark.util.StatCounter.<init>(StatCounter.scala:35)
    at org.apache.spark.util.StatCounter$.apply(StatCounter.scala:144)
    at org.apache.spark.rdd.DoubleRDDFunctions$$anonfun$stats$1$$anonfun$apply$1.apply(DoubleRDDFunctions.scala:42)
    at org.apache.spark.rdd.DoubleRDDFunctions$$anonfun$stats$1$$anonfun$apply$1.apply(DoubleRDDFunctions.scala:42)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
    at org.apache.spark.scheduler.Task.run(Task.scala:89)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
    at jdk.nashorn.internal.runtime.arrays.IteratorAction.apply(IteratorAction.java:116)
    at jdk.nashorn.internal.objects.NativeArray.forEach(NativeArray.java:1609)
    at jdk.nashorn.internal.scripts.Script$169$ranking_metrics_example.:program(examples/mllib/ranking_metrics_example.js:92)
    at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:640)
    at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:228)
    at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
    at jdk.nashorn.internal.runtime.Context.evaluateSource(Context.java:1219)
    at jdk.nashorn.internal.runtime.Context.load(Context.java:841)
    at jdk.nashorn.internal.objects.Global.load(Global.java:1536)
    at jdk.nashorn.internal.scripts.Script$168$\^eval\_.:program(<eval>:1)
    at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:640)
    at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:228)
    at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
    at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:446)
    at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:403)
    at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:399)
    at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
    at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
    at org.eclairjs.nashorn.SparkJS.loadJS(SparkJS.java:77)
    at org.eclairjs.nashorn.SparkJS.main(SparkJS.java:44)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 419.0 failed 1 times, most recent failure: Lost task 1.0 in stage 419.0 (TID 349, localhost): java.lang.ArrayIndexOutOfBoundsException: 4
    at scala.runtime.ScalaRunTime$.array_apply(ScalaRunTime.scala:71)
    at org.apache.spark.mllib.evaluation.RankingMetrics$$anonfun$ndcgAt$2.apply(RankingMetrics.scala:143)
    at org.apache.spark.mllib.evaluation.RankingMetrics$$anonfun$ndcgAt$2.apply(RankingMetrics.scala:132)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at org.apache.spark.util.StatCounter.merge(StatCounter.scala:53)
    at org.apache.spark.util.StatCounter.<init>(StatCounter.scala:35)
    at org.apache.spark.util.StatCounter$.apply(StatCounter.scala:144)
    at org.apache.spark.rdd.DoubleRDDFunctions$$anonfun$stats$1$$anonfun$apply$1.apply(DoubleRDDFunctions.scala:42)
    at org.apache.spark.rdd.DoubleRDDFunctions$$anonfun$stats$1$$anonfun$apply$1.apply(DoubleRDDFunctions.scala:42)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
    at org.apache.spark.scheduler.Task.run(Task.scala:89)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
    at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1431)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1419)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1418)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
    at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1418)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
    at scala.Option.foreach(Option.scala:236)
    at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:799)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1640)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1599)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1588)
    at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
    at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:620)
    at org.apache.spark.SparkContext.runJob(SparkContext.scala:1832)
    at org.apache.spark.SparkContext.runJob(SparkContext.scala:1952)
    at org.apache.spark.rdd.RDD$$anonfun$reduce$1.apply(RDD.scala:1025)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
    at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
    at org.apache.spark.rdd.RDD.reduce(RDD.scala:1007)
    at org.apache.spark.rdd.DoubleRDDFunctions$$anonfun$stats$1.apply(DoubleRDDFunctions.scala:42)
    at org.apache.spark.rdd.DoubleRDDFunctions$$anonfun$stats$1.apply(DoubleRDDFunctions.scala:42)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
    at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
    at org.apache.spark.rdd.DoubleRDDFunctions.stats(DoubleRDDFunctions.scala:41)
    at org.apache.spark.rdd.DoubleRDDFunctions$$anonfun$mean$1.apply$mcD$sp(DoubleRDDFunctions.scala:47)
    at org.apache.spark.rdd.DoubleRDDFunctions$$anonfun$mean$1.apply(DoubleRDDFunctions.scala:47)
    at org.apache.spark.rdd.DoubleRDDFunctions$$anonfun$mean$1.apply(DoubleRDDFunctions.scala:47)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
    at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
    at org.apache.spark.rdd.DoubleRDDFunctions.mean(DoubleRDDFunctions.scala:46)
    at org.apache.spark.mllib.evaluation.RankingMetrics.ndcgAt(RankingMetrics.scala:156)
    at jdk.nashorn.internal.scripts.Script$Recompilation$272$4229A$evaluation.ndcgAt(jar:file:/Users/doronrosenberg/mystuff/ibm/eclairjs/git/eclairjs-nashorn/./target/eclairjs-nashorn-0.1.jar!/mllib/evaluation.js:128)
    at jdk.nashorn.internal.scripts.Script$Recompilation$209$2573AJA$ranking_metrics_example.L:92(examples/mllib/ranking_metrics_example.js:94)
    at jdk.nashorn.internal.objects.NativeArray$9.forEach(NativeArray.java:1606)
    at jdk.nashorn.internal.runtime.arrays.IteratorAction.apply(IteratorAction.java:110)
    ... 28 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 4
    at scala.runtime.ScalaRunTime$.array_apply(ScalaRunTime.scala:71)
    at org.apache.spark.mllib.evaluation.RankingMetrics$$anonfun$ndcgAt$2.apply(RankingMetrics.scala:143)
    at org.apache.spark.mllib.evaluation.RankingMetrics$$anonfun$ndcgAt$2.apply(RankingMetrics.scala:132)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at org.apache.spark.util.StatCounter.merge(StatCounter.scala:53)
    at org.apache.spark.util.StatCounter.<init>(StatCounter.scala:35)
    at org.apache.spark.util.StatCounter$.apply(StatCounter.scala:144)
    at org.apache.spark.rdd.DoubleRDDFunctions$$anonfun$stats$1$$anonfun$apply$1.apply(DoubleRDDFunctions.scala:42)
    at org.apache.spark.rdd.DoubleRDDFunctions$$anonfun$stats$1$$anonfun$apply$1.apply(DoubleRDDFunctions.scala:42)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
    at org.apache.spark.scheduler.Task.run(Task.scala:89)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by doronrosenberg** [comment]
It definitely seems to be the RankingMetrics.ndcgAt(5) call that is causing this, no idea as to why.

**Comment by doronrosenberg** [comment]
The java version doesn't have this issue so reopneing

**Comment by Brian-P-Burns** [comment]
Found the issue.  In the example a variable was not being declared properly.
