### ISSUE TITLE
Twitter example does not work on cluster

### ISSUE THREAD

**Issue by pberkland** [EclairJS/eclairjs-nashorn#178]
Not sure if it has anything to do with our code, is authentication error.
The same command works on the same machine when spark master is local[*]

16/03/17 08:38:28 ERROR scheduler.ReceiverTracker: Deregistered receiver for stream 0: Restarting receiver with delay 2000ms: Error starting Twitter stream - java.lang.IllegalStateException: Authentication credentials are missing. See http://twitter4j.org/en/configuration.html for details
    at twitter4j.TwitterBaseImpl.ensureAuthorizationEnabled(TwitterBaseImpl.java:215)
    at twitter4j.TwitterStreamImpl.sample(TwitterStreamImpl.java:161)
    at org.apache.spark.streaming.twitter.TwitterReceiver.onStart(TwitterInputDStream.scala:93)
    at org.apache.spark.streaming.receiver.ReceiverSupervisor.startReceiver(ReceiverSupervisor.scala:148)
    at org.apache.spark.streaming.receiver.ReceiverSupervisor$$anonfun$restartReceiver$1.apply$mcV$sp(ReceiverSupervisor.scala:197)
    at org.apache.spark.streaming.receiver.ReceiverSupervisor$$anonfun$restartReceiver$1.apply(ReceiverSupervisor.scala:188)
    at org.apache.spark.streaming.receiver.ReceiverSupervisor$$anonfun$restartReceiver$1.apply(ReceiverSupervisor.scala:188)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by pberkland** [comment]
The twitter examples pass the Authorization token via System.properties.  For some reason the system.properties values are lost when running on a cluster.  This works ok on Java, Scala, and local mode.

I think the auth is gotten from the properties only on the master node, not the workers.

**Comment by pberkland** [comment]
Changed the example to use an alternate authorization which does require the use of System.properties.  We should still understand why the properties auth mechanism does not work in case it is a symptom of a larger underlying issue.

**Comment by pberkland** [comment]
The java example also fails on a cluster, so there is no unique eclairjs problem
