### ISSUE TITLE
require issue with Row

### ISSUE THREAD

**Issue by doronrosenberg** [EclairJS/eclairjs-nashorn#202]
Code: 

```
var jsc = new SparkContext("local[*]", "sql.Row Integration Tests");
var DataTypes = require(EclairJS_Globals.NAMESPACE + '/sql/types/DataTypes');
var structField1 = DataTypes.createStructField("surname", DataTypes.StringType, true);
var structField2 = DataTypes.createStructField("forename", DataTypes.StringType, true);
var structField3 = DataTypes.createStructField("age", DataTypes.IntegerType, true);
var structField4 = DataTypes.createStructField("birthday", DataTypes.DateType, true);
var structField5 = DataTypes.createStructField("numkids", DataTypes.IntegerType, true);
var structField6 = DataTypes.createStructField("married", DataTypes.BooleanType, true);
var structField7 = DataTypes.createStructField("networth", DataTypes.DoubleType, true);
var structField8 = DataTypes.createStructField("weight", DataTypes.DoubleType, true);
var structField9 = DataTypes.createStructField("percent", DataTypes.DoubleType, true);
var structField10 = DataTypes.createStructField("birthdaytime", DataTypes.TimestampType, true);
var rdd1 = jsc.textFile("/Users/doronrosenberg/mystuff/ibm/eclairjs/git/eclairjs-node/examples/rockers.txt");
var SQLContext = require(EclairJS_Globals.NAMESPACE + '/sql/SQLContext');
var sqlcontext1 = new SQLContext(jsc);
var structType1 = DataTypes.createStructType([structField1, structField2, structField3, structField4, structField5, structField6, structField7, structField8, structField9, structField10]);
var rdd2 = rdd1.map(function (line) {
    var parts = line.split(",");
    return rocker = {
      surname: parts[0],
      forename: parts[1],
      age: parts[2] ? parseInt(parts[2]) : null,
      birthday: parts[3] ? parts[3] : null,
      numkids: parts[4] ? parseInt(parts[4]) : null,
      married: parts[5] ? JSON.parse(parts[5]) : null,
      networth: parts[6] ? parseFloat(parts[6]) : null,
      weight: parts[7] ? parseFloat(parts[7]) : null,
      percent: parts[8] ? parseFloat(parts[8]) : null
    };
  });
var RowFactory = require(EclairJS_Globals.NAMESPACE + '/sql/RowFactory');
var rdd3 = rdd2.map(function (rocker, RowFactory){
    //print('create rocker: ',JSON.stringify(rocker));
    // Have to convert the Date and Timestamp fields
    var bday = new SqlDate(rocker.birthday);
    var bdaytime = new SqlTimestamp(rocker.birthday);
    return RowFactory.create([rocker.surname, rocker.forename, rocker.age, bday, rocker.numkids, rocker.married, rocker.networth, rocker.weight, rocker.percent, bdaytime]);
  }, [RowFactory]);
var dataFrame1 = sqlcontext1.createDataFrame(rdd3, structType1);
var DataFrame = require(EclairJS_Globals.NAMESPACE + '/sql/DataFrame');
dataFrame1.registerTempTable("rockstars");
var dataFrame2 = sqlcontext1.sql("SELECT * FROM rockstars");
var rdd4 = dataFrame2.toRDD();
var rdd5 = rdd4.map(function (row) {
              //print('toRDD.map row: ',row);
              // surname is at index=0
              return "Surname: " + row.getString(0);
            });
rdd5.count()
```

results in: 

```
Name: java.lang.RuntimeException
Message: org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 2.0 failed 1 times, most recent failure: Lost task 1.0 in stage 2.0 (TID 3, localhost): javax.script.ScriptException: ReferenceError: "SqlDate" is not defined in jar:file:/Users/doronrosenberg/mystuff/ibm/eclairjs/git/eclairjs-nashorn/target/eclairjs-nashorn-0.4-SNAPSHOT-jar-with-dependencies.jar!/eclairjs/Utils.js at line number 266 at column number 8
    at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:467)
    at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:389)
    at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
    at org.eclairjs.nashorn.JSFunction.call(JSFunction.java:48)
    at org.apache.spark.api.java.JavaPairRDD$$anonfun$toScalaFunction$1.apply(JavaPairRDD.scala:1015)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
    at org.apache.spark.util.Utils$.getIteratorSize(Utils.scala:1597)
    at org.apache.spark.rdd.RDD$$anonfun$count$1.apply(RDD.scala:1143)
    at org.apache.spark.rdd.RDD$$anonfun$count$1.apply(RDD.scala:1143)
    at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
    at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
    at org.apache.spark.scheduler.Task.run(Task.scala:89)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: jar:file:/Users/doronrosenberg/mystuff/ibm/eclairjs/git/eclairjs-nashorn/target/eclairjs-nashorn-0.4-SNAPSHOT-jar-with-dependencies.jar!/eclairjs/Utils.js:266:8 ReferenceError: "SqlDate" is not defined
    at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
    at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:319)
    at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:291)
    at jdk.nashorn.internal.objects.Global.__noSuchProperty__(Global.java:1432)
    at jdk.nashorn.internal.scripts.Script$Recompilation$160$Utils.L:1(jar:file:/Users/doronrosenberg/mystuff/ibm/eclairjs/git/eclairjs-nashorn/target/eclairjs-nashorn-0.4-SNAPSHOT-jar-with-dependencies.jar!/eclairjs/Utils.js#251:15<eval>:4)
    at jdk.nashorn.internal.scripts.Script$Recompilation$140$Utils.Utils_invoke(jar:file:/Users/doronrosenberg/mystuff/ibm/eclairjs/git/eclairjs-nashorn/target/eclairjs-nashorn-0.4-SNAPSHOT-jar-with-dependencies.jar!/eclairjs/Utils.js:261)
    at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:631)
    at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:228)
    at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
    at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
    at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:383)
    ... 19 more

Driver stacktrace:
StackTrace: jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:397)
jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:446)
jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:403)
jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:399)
jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
org.eclairjs.nashorn.JavascriptInterpreter$$anonfun$2$$anonfun$apply$1.apply(JavascriptInterpreter.scala:197)
org.eclairjs.nashorn.JavascriptInterpreter$$anonfun$2$$anonfun$apply$1.apply(JavascriptInterpreter.scala:197)
org.apache.toree.global.StreamState$.withStreams(StreamState.scala:81)
org.eclairjs.nashorn.JavascriptInterpreter$$anonfun$2.apply(JavascriptInterpreter.scala:195)
org.eclairjs.nashorn.JavascriptInterpreter$$anonfun$2.apply(JavascriptInterpreter.scala:195)
scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by jtbarbetta** [comment]
Since you are calling new on both SqlDate and SqlTimestamp within the map() lambda function you have to require those modules before using them and bind them to the lambda (for clustered env).  I modified the "map" section to be that as shown below and everything runs fine both in local and clustered mode now:
var RowFactory = require('eclairjs/sql/RowFactory');
var SqlDate = require('eclairjs/sql/SqlDate');
var SqlTimestamp = require('eclairjs/sql/SqlTimestamp');
var rdd3 = rdd2.map(function (rocker, RowFactory, SqlDate, SqlTimestamp){
    //print('create rocker: ',JSON.stringify(rocker));
    // Have to convert the Date and Timestamp fields
    var bday = new SqlDate(rocker.birthday);
    var bdaytime = new SqlTimestamp(rocker.birthday);
    return RowFactory.create([rocker.surname, rocker.forename, rocker.age, bday, rocker.numkids, rocker.married, rocker.networth, rocker.weight, rocker.percent, bdaytime]);
  }, [RowFactory, SqlDate, SqlTimestamp]);
