### ISSUE TITLE
Issue with Tuple3 and paralellize

### ISSUE THREAD

**Issue by doronrosenberg** [EclairJS/eclairjs-nashorn#271]
Using bin/eclairjs.sh

``` javascript
    var sparkConf = new SparkConf().setAppName("PowerIterationClusteringExample");
    var sc = new SparkContext(sparkConf);
    var Tuple3 = require(EclairJS_Globals.NAMESPACE + '/Tuple3');
    var rdd1 = sc.parallelize([new Tuple3(0, 1, 0.9)]);

    var PowerIterationClustering = require(EclairJS_Globals.NAMESPACE + '/mllib/clustering').PowerIterationClustering;
    var powerIterationClustering1 = new PowerIterationClustering();
    var powerIterationClustering2 = powerIterationClustering1.setK(2);
    var powerIterationClustering3 = powerIterationClustering2.setMaxIterations(10);
    var powerIterationClusteringModel1 = powerIterationClustering3.run(rdd1);

    return powerIterationClusteringModel1.assignments().collect();

```

throws:

```
Name: java.lang.RuntimeException
Message: org.apache.spark.SparkException: Job aborted due to stage failure: Task 7 in stage 972.0 failed 1 times, most recent failure: Lost task 7.0 in stage 972.0 (TID 1186, localhost): java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
    at org.eclairjs.nashorn.mllib.clustering.PowerIterationClusteringRunFunction.call(PowerIterationClusteringRunFunction.java:41)
    at org.apache.spark.api.java.JavaPairRDD$$anonfun$toScalaFunction$1.apply(JavaPairRDD.scala:1015)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
    at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at org.apache.spark.graphx.EdgeRDD$$anonfun$1.apply(EdgeRDD.scala:108)
    at org.apache.spark.graphx.EdgeRDD$$anonfun$1.apply(EdgeRDD.scala:106)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$22.apply(RDD.scala:745)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$22.apply(RDD.scala:745)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
    at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:69)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:268)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
    at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
    at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
    at org.apache.spark.scheduler.Task.run(Task.scala:89)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
StackTrace: jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:397)
jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:446)
jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:403)
jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:399)
jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
org.eclairjs.nashorn.JavascriptInterpreter$$anonfun$2$$anonfun$apply$1.apply(JavascriptInterpreter.scala:199)
org.eclairjs.nashorn.JavascriptInterpreter$$anonfun$2$$anonfun$apply$1.apply(JavascriptInterpreter.scala:199)
org.apache.toree.global.StreamState$.withStreams(StreamState.scala:81)
org.eclairjs.nashorn.JavascriptInterpreter$$anonfun$2.apply(JavascriptInterpreter.scala:197)
org.eclairjs.nashorn.JavascriptInterpreter$$anonfun$2.apply(JavascriptInterpreter.scala:197)
scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by billreed63** [comment]
The tuples passed to powerIterationClustering must be floats

```
   var rdd1 = sc.parallelize([new Tuple3(0.0, 1.0, 0.9)]);

    var PowerIterationClustering = require(EclairJS_Globals.NAMESPACE + '/mllib/clustering').PowerIterationClustering;
    var powerIterationClustering1 = new PowerIterationClustering();
    var powerIterationClustering2 = powerIterationClustering1.setK(2);
    var powerIterationClustering3 = powerIterationClustering2.setMaxIterations(10);
    var powerIterationClusteringModel1 = powerIterationClustering3.run(rdd1);

    return powerIterationClusteringModel1.assignments().collect();

```

**Comment by doronrosenberg** [comment]
This used to work so something changed', I'll fix the node examples
